# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            KnowledgeLog
tagline:          Log stuff
url:              http://emilw.github.io
paginate:         1
baseurl:          /
author:
  name:           Emil W
  url:            http://emilw.github.io
  email:          emil@postback.se

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/emilw/
