# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Setup
title:            KnowledgeLog
tagline:          Log stuff
url:              http://emilw.github.io
#paginate:         5
baseurl:          ""

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/emilw/

description: > # this means to ignore newlines until "baseurl:"
  This site is intended to be a collection of quick references for different stuff 
  that i have worked with. The content can be everything from notes to guides
  and the quality can vary.
github_username:  emilw


# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
